const lista_productos = [
    {id:1,visibilidad:true, tipo:"silla", precio:20000, imagen:"http://woodworkcenter.netlify.app//img/sillas/silla_1.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"silla | color caoba"},
    {id:2,visibilidad:true, tipo:"silla", precio:20000, imagen:"http://woodworkcenter.netlify.app//img/sillas/silla_2.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"silla | color caoba"},
    {id:3,visibilidad:true, tipo:"silla", precio:20000, imagen:"http://woodworkcenter.netlify.app//img/sillas/silla_3.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"silla | color caoba"},
    {id:4,visibilidad:true, tipo:"silla", precio:20000, imagen:"http://woodworkcenter.netlify.app//img/sillas/silla_4.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"silla | color caoba"},
    {id:5,visibilidad:true, tipo:"silla", precio:20000, imagen:"http://woodworkcenter.netlify.app//img/sillas/silla_5.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"silla | color caoba"},
    {id:6,visibilidad:true, tipo:"silla", precio:20000, imagen:"http://woodworkcenter.netlify.app//img/sillas/silla_6.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"silla | color caoba"},
    {id:7,visibilidad:true, tipo:"silla", precio:20000, imagen:"http://woodworkcenter.netlify.app//img/sillas/silla_7.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"silla | color caoba"},
    {id:8.1,visibilidad:true, tipo:"mesa", precio:35000, imagen:"http://woodworkcenter.netlify.app//img/mesas/mesa_8.1.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"Mesa larga | Caoba"},
    {id:8.2,visibilidad:false, tipo:"mesa", precio:38000, imagen:"http://woodworkcenter.netlify.app//img/mesas/mesa_8.1.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 15 x 25 x 5", nombre:"Mesa larga | Caoba"},
    {id:8.3,visibilidad:false, tipo:"mesa", precio:41000, imagen:"http://woodworkcenter.netlify.app//img/mesas/mesa_8.1.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 18 x 25 x 5", nombre:"Mesa larga | Caoba"},
    {id:9,visibilidad:true, tipo:"mesa", precio:35000, imagen:"http://woodworkcenter.netlify.app//img/mesas/mesa_9.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"Mesa larga | Caoba"},
    {id:10,visibilidad:true, tipo:"mesa", precio:35000, imagen:"http://woodworkcenter.netlify.app//img/mesas/mesa_10.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"Mesa larga | Caoba"},
    {id:11,visibilidad:true, tipo:"mesa", precio:35000, imagen:"http://woodworkcenter.netlify.app//img/mesas/mesa_11.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"Mesa larga | Caoba"},
    {id:12,visibilidad:true, tipo:"mesa", precio:35000, imagen:"http://woodworkcenter.netlify.app//img/mesas/mesa_12.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"Mesa larga | Caoba"},
    {id:13,visibilidad:true, tipo:"mesa", precio:35000, imagen:"http://woodworkcenter.netlify.app//img/mesas/mesa_13.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"Mesa larga | Caoba"},
    {id:14,visibilidad:true, tipo:"mesa de luz", precio:35000, imagen:"http://woodworkcenter.netlify.app//img/mesas_de_luz/mesa_de_luz-14.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"Mesa de luz | color blanco"},
    {id:15,visibilidad:true, tipo:"mesa de luz", precio:35000, imagen:"http://woodworkcenter.netlify.app//img/mesas_de_luz/mesa_de_luz-15.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"Mesa de luz | color blanco"},
    {id:16,visibilidad:true, tipo:"estante", precio:45000, imagen:"http://woodworkcenter.netlify.app//img/estantes/estante_16.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"estante | color palido"},
    {id:17,visibilidad:true, tipo:"estante", precio:45000, imagen:"http://woodworkcenter.netlify.app//img/estantes/estante_17.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "estante | color palido"},
    {id:18,visibilidad:true, tipo:"comoda", precio:70500, imagen:"http://woodworkcenter.netlify.app//img/comodas/comoda_18.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "comoda | blanco con madera de pino"},
    {id:19,visibilidad:true, tipo:"comoda", precio:70500, imagen:"http://woodworkcenter.netlify.app//img/comodas/comoda_19.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "comoda | blanco con madera de pino"},
    {id:20,visibilidad:true, tipo:"comoda", precio:70500, imagen:"http://woodworkcenter.netlify.app//img/comodas/comoda_20.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "comoda | blanco con madera de pino"},
    {id:21,visibilidad:true, tipo:"comoda", precio:70500, imagen:"http://woodworkcenter.netlify.app//img/comodas/comoda_21.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "comoda | blanco con madera de pino"},
    {id:22,visibilidad:true, tipo:"comoda", precio:70500, imagen:"http://woodworkcenter.netlify.app//img/comodas/comoda_22.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "comoda | blanco con madera de pino"},
    {id:23,visibilidad:true, tipo:"comoda", precio:70500, imagen:"http://woodworkcenter.netlify.app//img/comodas/comoda_23.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "comoda | blanco con madera de pino"},
    {id:24,visibilidad:true, tipo:"comoda", precio:70500, imagen:"http://woodworkcenter.netlify.app//img/comodas/comoda_24.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "comoda | blanco con madera de pino"},
    {id:25,visibilidad:true, tipo:"comoda", precio:70500, imagen:"http://woodworkcenter.netlify.app//img/comodas/comoda_25.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "comoda | blanco con madera de pino"},
    {id:26,visibilidad:true, tipo:"comoda", precio:70500, imagen:"http://woodworkcenter.netlify.app//img/comodas/comoda_26.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "comoda | blanco con madera de pino"},
    {id:27,visibilidad:true, tipo:"comoda", precio:70500, imagen:"http://woodworkcenter.netlify.app//img/comodas/comoda_27.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "comoda | blanco con madera de pino"},
    {id:28,visibilidad:true, tipo:"comoda", precio:70500, imagen:"http://woodworkcenter.netlify.app//img/comodas/comoda_28.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "comoda | blanco con madera de pino"},
    {id:29,visibilidad:true, tipo:"armario", precio:70000, imagen:"http://woodworkcenter.netlify.app//img/armario/armario_29.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "armario | blanco "},
    {id:30,visibilidad:true, tipo:"armario", precio:70000, imagen:"http://woodworkcenter.netlify.app//img/armario/armario_30.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "armario | blanco "},
    {id:31,visibilidad:true, tipo:"armario", precio:70000, imagen:"http://woodworkcenter.netlify.app//img/armario/armario_31.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "armario | blanco "},
    
]

localStorage.setItem("Productos", JSON.stringify(lista_productos))

const Productos_carrito=JSON.parse(localStorage.getItem("Carrito"))

let carrito_Ls = []
if(carrito_Ls !==null){
    carrito_Ls=Productos_carrito || localStorage.setItem("Carrito",JSON.stringify( carrito_Ls))
}



let Producto_Pago = []
const Producto_PagoLS = JSON.parse(localStorage.getItem("Productos-pagar"))

if (Producto_Pago !== null){
    Producto_Pago = Producto_PagoLS|| localStorage.setItem("Productos-pagar",JSON.stringify(Producto_Pago))
}

