
const lista_productos = [
    {id:1,visibilidad:true, nombre: "SILLA | Astor negro ", tipo:"silla", precio:70000, imagen:"http://127.0.0.1:5500/img/sillas/silla_1.jpg", descripcion: "Silla Astor hecha en paraiso laqueado negro con veta abierta", medidas:"Medida: 54x45x80h"},
    {id:2,visibilidad:true, nombre: "SILLA | Paraiso ", tipo:"silla", precio:65000, imagen:"http://127.0.0.1:5500/img/sillas/silla_2.jpg", descripcion: "Silla Astor hecha en madera paraiso", medidas:"Medida: 54x45x80h"},
    {id:3,visibilidad:true, nombre: "SILLA | Astor apoya brazos ", tipo:"silla", precio:75000, imagen:"http://127.0.0.1:5500/img/sillas/silla_3.jpg", descripcion: "Silla con apoyabrazos hecha en madera veteada laqueada negra", medidas:"Medida: 63x45x82h"},
    {id:4,visibilidad:true, nombre: "BANQUETA | Oslo simple ", tipo:"silla", precio:70000, imagen:"http://127.0.0.1:5500/img/sillas/silla_4.jpg", descripcion: "Banqueta hecha en peteribí, diseñada y producida por Nosotros", medidas:"Medida: 43x43x66 cm"},
    {id:5,visibilidad:true, nombre: "BANQUETA | Oslo ", tipo:"silla", precio:75000, imagen:"http://127.0.0.1:5500/img/sillas/silla_5.jpg", descripcion: "Banqueta hecha en peteribí, diseñada y producida por Nosotros", medidas:"Medida: 40x40x90h cm"},
    
    {id:6,visibilidad:true, nombre: "ESTANTERIA | Stick TV ", tipo:"estante", precio:"Precio segun medida", imagen:"http://127.0.0.1:5500/img/estantes/estante_6.jpg", descripcion: "Estructura maciza de incienso o peteribí, con sticks o ménsulas de hierro en diferentes colores. Estantes enchapado melaminico laca o enchapados en roble americano, incienso o goiabao tostado. Diseño minimalista y vérsatil pero a su vez elegante y sobrio pensando en el hábitat contemporáneo del interiorismo. ", medidas:"Sin medida"},
    {id:7,visibilidad:true, nombre: "ESTANTERIA | Stick Full Madera ", tipo:"estante", precio:100000, imagen:"http://127.0.0.1:5500/img/estantes/estante_7.jpg", descripcion: "Estructura maciza de incienso o peteribí, con sticks o ménsulas de hierro en diferentes colores. Estantes enchapado melaminico laca o enchapados en roble americano, incienso o goiabao tostado. Diseño minimalista y vérsatil pero a su vez elegante y sobrio pensando en el hábitat contemporáneo del interiorismo. ", medidas:"Medida: 50x32px150h"},
    {id:7.1,visibilidad:false, nombre: "ESTANTERIA | Stick Full Madera ", tipo:"estante", precio:150000, imagen:"http://127.0.0.1:5500/img/estantes/estante_7.jpg", descripcion: "Estructura maciza de incienso o peteribí, con sticks o ménsulas de hierro en diferentes colores. Estantes enchapado melaminico laca o enchapados en roble americano, incienso o goiabao tostado. Diseño minimalista y vérsatil pero a su vez elegante y sobrio pensando en el hábitat contemporáneo del interiorismo. ", medidas:"Medida: 100x32px150h"},
    {id:7.2,visibilidad:false, nombre: "ESTANTERIA | Stick Full Madera ", tipo:"estante", precio:180000, imagen:"http://127.0.0.1:5500/img/estantes/estante_7.jpg", descripcion: "Estructura maciza de incienso o peteribí, con sticks o ménsulas de hierro en diferentes colores. Estantes enchapado melaminico laca o enchapados en roble americano, incienso o goiabao tostado. Diseño minimalista y vérsatil pero a su vez elegante y sobrio pensando en el hábitat contemporáneo del interiorismo. ", medidas:"Medida: 150x32px150h"},
    {id:7.3,visibilidad:false, nombre: "ESTANTERIA | Stick Full Madera ", tipo:"estante", precio:200000, imagen:"http://127.0.0.1:5500/img/estantes/estante_7.jpg", descripcion: "Estructura maciza de incienso o peteribí, con sticks o ménsulas de hierro en diferentes colores. Estantes enchapado melaminico laca o enchapados en roble americano, incienso o goiabao tostado. Diseño minimalista y vérsatil pero a su vez elegante y sobrio pensando en el hábitat contemporáneo del interiorismo. ", medidas:"Medida: 200x32px150h"},
    {id:7.4,visibilidad:false, nombre: "ESTANTERIA | Stick Full Madera ", tipo:"estante", precio:250000, imagen:"http://127.0.0.1:5500/img/estantes/estante_7.jpg", descripcion: "Estructura maciza de incienso o peteribí, con sticks o ménsulas de hierro en diferentes colores. Estantes enchapado melaminico laca o enchapados en roble americano, incienso o goiabao tostado. Diseño minimalista y vérsatil pero a su vez elegante y sobrio pensando en el hábitat contemporáneo del interiorismo. ", medidas:"Medida: 250x32px150h"},
    {id:8,visibilidad:true, nombre: "ESTANTERIA | Stick", tipo:"estante", precio:70000, imagen:"http://127.0.0.1:5500/img/estantes/estante_8.jpg", descripcion: "Estructura maciza de incienso o peteribí, con sticks o ménsulas de hierro en diferentes colores. Estantes enchapado melaminico laca o enchapados en roble americano, incienso o goiabao tostado. Diseño minimalista y vérsatil pero a su vez elegante y sobrio pensando en el hábitat contemporáneo del interiorismo. ", medidas:"Medida: 50x32px150h"},
    {id:8.1,visibilidad:false, nombre: "ESTANTERIA | Stick", tipo:"estante", precio:80000, imagen:"http://127.0.0.1:5500/img/estantes/estante_8.jpg", descripcion: "Estructura maciza de incienso o peteribí, con sticks o ménsulas de hierro en diferentes colores. Estantes enchapado melaminico laca o enchapados en roble americano, incienso o goiabao tostado. Diseño minimalista y vérsatil pero a su vez elegante y sobrio pensando en el hábitat contemporáneo del interiorismo. ", medidas:"Medida: 100x32px150h"},
    {id:8.2,visibilidad:false, nombre: "ESTANTERIA | Stick", tipo:"estante", precio:100000, imagen:"http://127.0.0.1:5500/img/estantes/estante_8.jpg", descripcion: "Estructura maciza de incienso o peteribí, con sticks o ménsulas de hierro en diferentes colores. Estantes enchapado melaminico laca o enchapados en roble americano, incienso o goiabao tostado. Diseño minimalista y vérsatil pero a su vez elegante y sobrio pensando en el hábitat contemporáneo del interiorismo. ", medidas:"Medida: 150x32px150h"},
    {id:8.3,visibilidad:false, nombre: "ESTANTERIA | Stick", tipo:"estante", precio:120000, imagen:"http://127.0.0.1:5500/img/estantes/estante_8.jpg", descripcion: "Estructura maciza de incienso o peteribí, con sticks o ménsulas de hierro en diferentes colores. Estantes enchapado melaminico laca o enchapados en roble americano, incienso o goiabao tostado. Diseño minimalista y vérsatil pero a su vez elegante y sobrio pensando en el hábitat contemporáneo del interiorismo. ", medidas:"Medida: 200x32px150h"},
    {id:8.4,visibilidad:false, nombre: "ESTANTERIA | Stick", tipo:"estante", precio:150000, imagen:"http://127.0.0.1:5500/img/estantes/estante_8.jpg", descripcion: "Estructura maciza de incienso o peteribí, con sticks o ménsulas de hierro en diferentes colores. Estantes enchapado melaminico laca o enchapados en roble americano, incienso o goiabao tostado. Diseño minimalista y vérsatil pero a su vez elegante y sobrio pensando en el hábitat contemporáneo del interiorismo. ", medidas:"Medida: 250x32px150h"},
    
    {id:9,visibilidad:true, nombre: "Mesas | C-C base negro", tipo:"mesa", precio:110000,   imagen:"http://127.0.0.1:5500/img/mesas/mesa_9.jpg", descripcion: "Mesa de comedor C-C La Carpintería con base de chapa plegada y hierro con tapa enchapado natural en madera ", medidas:"Medida: 090"},
    {id:9.1,visibilidad:false, nombre: "Mesas | C-C base negro", tipo:"mesa", precio:125000,   imagen:"http://127.0.0.1:5500/img/mesas/mesa_9.jpg", descripcion: "Mesa de comedor C-C La Carpintería con base de chapa plegada y hierro con tapa enchapado natural en madera ", medidas:"Medida: 100"},
    {id:9.2,visibilidad:false, nombre: "Mesas | C-C base negro", tipo:"mesa", precio:130000,   imagen:"http://127.0.0.1:5500/img/mesas/mesa_9.jpg", descripcion: "Mesa de comedor C-C La Carpintería con base de chapa plegada y hierro con tapa enchapado natural en madera ", medidas:"Medida: 120"},
    {id:9.3,visibilidad:false, nombre: "Mesas | C-C base negro", tipo:"mesa", precio:150000,   imagen:"http://127.0.0.1:5500/img/mesas/mesa_9.jpg", descripcion: "Mesa de comedor C-C La Carpintería con base de chapa plegada y hierro con tapa enchapado natural en madera ", medidas:"Medida: 140"},
    {id:10,visibilidad:true, nombre: "Mesas | C-C full negro", tipo:"mesa", precio:150000, imagen:"http://127.0.0.1:5500/img/mesas/mesa_10.jpg", descripcion: "Mesa de comedor C-C La Carpintería con base de chapa plegada y hierro con tapa enchapado natural laqueado poliuretanico negro con veta abierta", medidas:"Medida: 090"},
    {id:10.1,visibilidad:false, nombre: "Mesas | C-C full negro", tipo:"mesa", precio:170000, imagen:"http://127.0.0.1:5500/img/mesas/mesa_10.jpg", descripcion: "Mesa de comedor C-C La Carpintería con base de chapa plegada y hierro con tapa enchapado natural laqueado poliuretanico negro con veta abierta", medidas:"Medida: 100"},
    {id:10.2,visibilidad:false, nombre: "Mesas | C-C full negro", tipo:"mesa", precio:220000, imagen:"http://127.0.0.1:5500/img/mesas/mesa_10.jpg", descripcion: "Mesa de comedor C-C La Carpintería con base de chapa plegada y hierro con tapa enchapado natural laqueado poliuretanico negro con veta abierta", medidas:"Medida: 120"},
    {id:10.3,visibilidad:false, nombre: "Mesas | C-C full negro", tipo:"mesa", precio:250000, imagen:"http://127.0.0.1:5500/img/mesas/mesa_10.jpg", descripcion: "Mesa de comedor C-C La Carpintería con base de chapa plegada y hierro con tapa enchapado natural laqueado poliuretanico negro con veta abierta", medidas:"Medida: 140"},
    {id:11,visibilidad:true, nombre: "Mesas | Mesa Oslo", tipo:"mesa", precio:290000, imagen:"http://127.0.0.1:5500/img/mesas/mesa_11.jpg", descripcion: "Mesa alta Oslo La Carpintería hecha en petiribí macizo con tapa enchapado natural en peteribi", medidas:"Medida: 130x130x75h"},
    {id:11.1,visibilidad:false, nombre: "Mesas | Mesa Oslo", tipo:"mesa", precio:250000, imagen:"http://127.0.0.1:5500/img/mesas/mesa_11.jpg", descripcion: "Mesa alta Oslo La Carpintería hecha en petiribí macizo con tapa enchapado natural en peteribi", medidas:"Medida: 150x90x75h"},
    {id:11.2,visibilidad:false, nombre: "Mesas | Mesa Oslo", tipo:"mesa", precio:300000, imagen:"http://127.0.0.1:5500/img/mesas/mesa_11.jpg", descripcion: "Mesa alta Oslo La Carpintería hecha en petiribí macizo con tapa enchapado natural en peteribi", medidas:"Medida: 200x90x75h"},
    {id:11.3,visibilidad:false, nombre: "Mesas | Mesa Oslo", tipo:"mesa", precio:320000, imagen:"http://127.0.0.1:5500/img/mesas/mesa_11.jpg", descripcion: "Mesa alta Oslo La Carpintería hecha en petiribí macizo con tapa enchapado natural en peteribi", medidas:"Medida: 240x90x75h"},
    {id:12,visibilidad:true, nombre: "Mesas | C-C base visión", tipo:"mesa", precio:110000, imagen:"http://127.0.0.1:5500/img/mesas/mesa_12.jpg", descripcion: "Mesa de comedor C-C La Carpintería con base de chapa plegada y hierro con tapa enchapado natural en madera ", medidas:"Medida: 090 "},
    {id:12.1,visibilidad:false, nombre: "Mesas | C-C base visión", tipo:"mesa", precio:130000, imagen:"http://127.0.0.1:5500/img/mesas/mesa_12.jpg", descripcion: "Mesa de comedor C-C La Carpintería con base de chapa plegada y hierro con tapa enchapado natural en madera ", medidas:"Medida: 100 "},
    {id:12.2,visibilidad:false, nombre: "Mesas | C-C base visión", tipo:"mesa", precio:150000, imagen:"http://127.0.0.1:5500/img/mesas/mesa_12.jpg", descripcion: "Mesa de comedor C-C La Carpintería con base de chapa plegada y hierro con tapa enchapado natural en madera ", medidas:"Medida: 120 "},
    {id:12.3,visibilidad:false, nombre: "Mesas | C-C base visión", tipo:"mesa", precio:170000, imagen:"http://127.0.0.1:5500/img/mesas/mesa_12.jpg", descripcion: "Mesa de comedor C-C La Carpintería con base de chapa plegada y hierro con tapa enchapado natural en madera ", medidas:"Medida: 140 "},
    
    {id:13,visibilidad:true, nombre: "Mesa de luz | Bandeja estante", tipo:"mesa de luz", precio:70000, imagen:"http://127.0.0.1:5500/img/mesas_de_luz/mesa_de_luz-13.jpg", descripcion: "Mesa de luz hecha en madera enchapa. Diseñada y producida por Nosotros", medidas:"Medida: 50x40x55h "},
    {id:14,visibilidad:true, nombre: "Mesa de luz | Bandeja", tipo:"mesa de luz", precio:75000, imagen:"http://127.0.0.1:5500/img/mesas_de_luz/mesa_de_luz-14.jpg", descripcion: "Mesa de luz hecha en madera enchapa. Diseñada y producida por Nosotros", medidas:"Medida: 50x40x55h"},
    
    {id:15,visibilidad:true, nombre: "Comoda | Trineo", tipo:"comoda", precio:300000, imagen:"http://127.0.0.1:5500/img/comodas/comoda_15.jpg", descripcion: "Mesa de luz hecha en madera enchapa. Diseñada y producida por Nosotros", medidas:"Medida: 50x40x55h"},
    {id:16,visibilidad:true, nombre: "Comoda | Serrano", tipo:"comoda", precio:290000, imagen:"http://127.0.0.1:5500/img/comodas/comoda_16.jpg", descripcion: "Mesa de luz hecha en madera enchapa. Diseñada y producida por Nosotros", medidas:"Medida: 50x40x55h"},
]

localStorage.setItem("Productos", JSON.stringify(lista_productos))

const Productos_carrito=JSON.parse(localStorage.getItem("Carrito"))

let carrito_Ls = []
if(carrito_Ls !==null){
    carrito_Ls=Productos_carrito || localStorage.setItem("Carrito",JSON.stringify( carrito_Ls))
}



let Producto_Pago = []
const Producto_PagoLS = JSON.parse(localStorage.getItem("Productos-pagar"))

if (Producto_Pago !== null){
    Producto_Pago = Producto_PagoLS|| localStorage.setItem("Productos-pagar",JSON.stringify(Producto_Pago))
}

