const lista_productos = [
    {id:1, tipo:"silla", precio:20000, imagen:"http://woodworkcenter.netlify.app//img/sillas/silla_1.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"silla | color caoba"},
    {id:2, tipo:"silla", precio:20000, imagen:"http://woodworkcenter.netlify.app//img/sillas/silla_2.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"silla | color caoba"},
    {id:3, tipo:"silla", precio:20000, imagen:"http://woodworkcenter.netlify.app//img/sillas/silla_3.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"silla | color caoba"},
    {id:4, tipo:"silla", precio:20000, imagen:"http://woodworkcenter.netlify.app//img/sillas/silla_4.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"silla | color caoba"},
    {id:5, tipo:"silla", precio:20000, imagen:"http://woodworkcenter.netlify.app//img/sillas/silla_5.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"silla | color caoba"},
    {id:6, tipo:"silla", precio:20000, imagen:"http://woodworkcenter.netlify.app//img/sillas/silla_6.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"silla | color caoba"},
    {id:7, tipo:"silla", precio:20000, imagen:"http://woodworkcenter.netlify.app//img/sillas/silla_7.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"silla | color caoba"},
    {id:8, tipo:"mesa", precio:35000, imagen:"http://woodworkcenter.netlify.app//img/mesas/mesa_8.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"Mesa larga | Caoba"},
    {id:9, tipo:"mesa", precio:35000, imagen:"http://woodworkcenter.netlify.app//img/mesas/mesa_9.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"Mesa larga | Caoba"},
    {id:10, tipo:"mesa", precio:35000, imagen:"http://woodworkcenter.netlify.app//img/mesas/mesa_10.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"Mesa larga | Caoba"},
    {id:11, tipo:"mesa", precio:35000, imagen:"http://woodworkcenter.netlify.app//img/mesas/mesa_11.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"Mesa larga | Caoba"},
    {id:12, tipo:"mesa", precio:35000, imagen:"http://woodworkcenter.netlify.app//img/mesas/mesa_12.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"Mesa larga | Caoba"},
    {id:13, tipo:"mesa", precio:35000, imagen:"http://woodworkcenter.netlify.app//img/mesas/mesa_13.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"Mesa larga | Caoba"},
    {id:14, tipo:"mesa de luz", precio:35000, imagen:"http://woodworkcenter.netlify.app//img/mesas_de_luz/mesa_de_luz-14.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"Mesa de luz | color blanco"},
    {id:15, tipo:"mesa de luz", precio:35000, imagen:"http://woodworkcenter.netlify.app//img/mesas_de_luz/mesa_de_luz-15.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"Mesa de luz | color blanco"},
    {id:16, tipo:"estante", precio:45000, imagen:"http://woodworkcenter.netlify.app//img/estantes/estante_16.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre:"estante | color palido"},
    {id:17, tipo:"estante", precio:45000, imagen:"http://woodworkcenter.netlify.app//img/estantes/estante_17.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "estante | color palido"},
    {id:18, tipo:"comoda", precio:70500, imagen:"http://woodworkcenter.netlify.app//img/comodas/comoda_18.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "comoda | blanco con madera de pino"},
    {id:19, tipo:"comoda", precio:70500, imagen:"http://woodworkcenter.netlify.app//img/comodas/comoda_19.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "comoda | blanco con madera de pino"},
    {id:20, tipo:"comoda", precio:70500, imagen:"http://woodworkcenter.netlify.app//img/comodas/comoda_20.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "comoda | blanco con madera de pino"},
    {id:21, tipo:"comoda", precio:70500, imagen:"http://woodworkcenter.netlify.app//img/comodas/comoda_21.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "comoda | blanco con madera de pino"},
    {id:22, tipo:"comoda", precio:70500, imagen:"http://woodworkcenter.netlify.app//img/comodas/comoda_22.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "comoda | blanco con madera de pino"},
    {id:23, tipo:"comoda", precio:70500, imagen:"http://woodworkcenter.netlify.app//img/comodas/comoda_23.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "comoda | blanco con madera de pino"},
    {id:24, tipo:"comoda", precio:70500, imagen:"http://woodworkcenter.netlify.app//img/comodas/comoda_24.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "comoda | blanco con madera de pino"},
    {id:25, tipo:"comoda", precio:70500, imagen:"http://woodworkcenter.netlify.app//img/comodas/comoda_25.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "comoda | blanco con madera de pino"},
    {id:26, tipo:"comoda", precio:70500, imagen:"http://woodworkcenter.netlify.app//img/comodas/comoda_26.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "comoda | blanco con madera de pino"},
    {id:27, tipo:"comoda", precio:70500, imagen:"http://woodworkcenter.netlify.app//img/comodas/comoda_27.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "comoda | blanco con madera de pino"},
    {id:28, tipo:"comoda", precio:70500, imagen:"http://woodworkcenter.netlify.app//img/comodas/comoda_28.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "comoda | blanco con madera de pino"},
    {id:29, tipo:"armario", precio:70000, imagen:"http://woodworkcenter.netlify.app//img/armario/armario_29.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "armario | blanco "},
    {id:30, tipo:"armario", precio:70000, imagen:"http://woodworkcenter.netlify.app//img/armario/armario_30.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "armario | blanco "},
    {id:31, tipo:"armario", precio:70000, imagen:"http://woodworkcenter.netlify.app//img/armario/armario_31.jpg", descripcion: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi molestias aspernatur, accusamus vitae recusandae natus? Dolorum illo ullam delectus laboriosam!", medidas:"Medida: 12 x 25 x 5", nombre: "armario | blanco "},
    
]

localStorage.setItem("Productos", JSON.stringify(lista_productos))

const Productos_carrito=JSON.parse(localStorage.getItem("Carrito"))

let carrito_Ls = []
if(carrito_Ls !==null){
    carrito_Ls=Productos_carrito || localStorage.setItem("Carrito",JSON.stringify( carrito_Ls))
}



let Producto_Pago = []
const Producto_PagoLS = JSON.parse(localStorage.getItem("Productos-pagar"))

if (Producto_Pago !== null){
    Producto_Pago = Producto_PagoLS|| localStorage.setItem("Productos-pagar",JSON.stringify(Producto_Pago))
}

